GET http://localhost:3003/api/user/me HTTP/1.1

Authorization: Bearer 

###

POST http://localhost:3003/api/auth/login

Content-Type: application/json


{
    "username" : "shivaluma",
    "password": "nguhamay"
}